FROM sail-8.0/app

USER root

# Install additional dependencies here
RUN apt-get update && \
    apt-get install -y \
        libwebp-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libxpm-dev \
        libfreetype6-dev \
        libonig-dev \
        libzip-dev \
        libmagickwand-dev

# Install Imagick extension
RUN pecl install imagick && docker-php-ext-enable imagick

# Install ImageMagick
RUN apt-get install -y imagemagick

# Install Composer dependencies
COPY composer.json composer.lock /var/www/html/
RUN composer install --no-scripts --no-autoloader

# Copy application files
COPY . /var/www/html

# Generate autoload files
RUN composer dump-autoload

USER sail
